<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TrackHub.Manager.Infrastructure.SecurityApi</RootNamespace>
    <AssemblyName>TrackHub.Manager.Infrastructure.SecurityApi</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GraphQL.Client" />
    <ProjectReference Include="$(RepoRoot)TrackHubCommon/src/Common.Infrastructure/Common.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Application\Application.csproj" />
  </ItemGroup>
</Project>