<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TrackHub.TripManagement.Domain</RootNamespace>
    <AssemblyName>TrackHub.TripManagement.Domain</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NetTopologySuite" />
    <ProjectReference Include="$(RepoRoot)TrackHubCommon/src/Common.Domain/Common.Domain.csproj" />
  </ItemGroup>
</Project>
