<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TrackHub.Router.Infrastructure.CommandTrack</RootNamespace>
    <AssemblyName>TrackHub.Router.Infrastructure.CommandTrack</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" />
    <ProjectReference Include="$(RepoRoot)TrackHubCommon/src/Common.Domain/Common.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Domain.csproj" />
  </ItemGroup>
</Project>