<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>TrackHub.Telemetry.Web</RootNamespace>
    <AssemblyName>TrackHub.Telemetry.Web</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Infrastructure\TelemetryDB\TelemetryDB.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GraphQL.Client.Serializer.SystemTextJson" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="TrackHubCommon.Web" />
    <PackageReference Include="HotChocolate.AspNetCore" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" />
  </ItemGroup>
</Project>
