<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TrackHub.Security.Infrastructure.ManagerApi</RootNamespace>
    <AssemblyName>TrackHub.Security.Infrastructure.ManagerApi</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GraphQL.Client" />
    <ProjectReference Include="$(RepoRoot)TrackHubCommon/src/Common.Infrastructure/Common.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Application\Application.csproj" />
  </ItemGroup>
</Project>