<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TrackHub.TripManagement.Infrastructure.ManagerApi</RootNamespace>
    <AssemblyName>TrackHub.TripManagement.Infrastructure.ManagerApi</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GraphQL.Client" />
    <PackageReference Include="TrackHubCommon.Infrastructure" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Domain.csproj" />
  </ItemGroup>
</Project>
